<a href="https://colab.research.google.com/github/Sadhana-up/PyTorch/blob/main/01_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
else:
    print("cuda is not available")

cuda is available


### Creating a Tensor

In [ ]:
# using empty
a = torch.empty(2,3) ##shape


In [ ]:
# type of tensor
type(a)

torch.Tensor

In [ ]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using rand -> value from 0 to 1 randomly
torch.rand(2,3)


tensor([[0.5160, 0.7487, 0.0500],
        [0.9029, 0.2382, 0.5125]])

In [ ]:
#manual seed
torch.manual_seed(100) # give same random value
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [ ]:
#Linspace :linearly spaced
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Tensor Shapes


In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.empty_like(x) ### shape chei x ko ley vanna khojeko ho

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3558464075923337525]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

Data Types

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [ ]:
torch.rand_like(x) ## not possible

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

Mathematical Operations

1.Scalar Operations

In [ ]:
a = torch.rand(2,2)

In [ ]:
a

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [ ]:
a+2
# a-2
# a*2
# a%2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

2. Element Wise Operation

In [ ]:
x = torch.rand(2,2)
y = torch.rand(2,2)
x


tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])

In [ ]:
y

tensor([[0.0169, 0.2209],
        [0.9535, 0.7064]])

In [ ]:
# add
x + y

tensor([[0.5446, 0.4681],
        [1.7444, 1.1299]])

In [ ]:
#sub
x-y

tensor([[ 0.5108,  0.0263],
        [-0.1627, -0.2829]])

In [ ]:
# power
x**y

tensor([[0.9893, 0.7344],
        [0.7996, 0.5450]])

In [ ]:
#mod
x%y

tensor([[0.0038, 0.0263],
        [0.7909, 0.4235]])