<a href="https://colab.research.google.com/github/Sadhana-up/PyTorch/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Automatic Differentiation to calculate dervative for NNs

In [2]:
import torch

In [3]:
x = torch.tensor(3.0,requires_grad=True) # pytorch understand tha we r trying to. calculate derivative

In [4]:
y = x**2 ## forward pass
x


tensor(3., requires_grad=True)

In [5]:
y

tensor(9., grad_fn=<PowBackward0>)

In [6]:
y.backward() ## gradient calculate vayo

In [7]:
x.grad

tensor(6.)

In [8]:

y = x **2

In [9]:
z = torch.sin(y)

In [10]:
y

tensor(9., grad_fn=<PowBackward0>)

In [11]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [12]:
# we need dz/dx so we need to use back propagation and use the chain rule : dz/dx = dz/dy * dy/dx

In [13]:
z.backward()

In [14]:
x.grad

tensor(0.5332)

In [15]:
x = torch.tensor(6.7) # Input Feature
y = torch.tensor(0.0) # True Label

w = torch.tensor(1.0) # Weight
b = torch.tensor(0.0) # Bias




In [17]:
# Binary Cross-Entropy Loss for scalar -> Calculate Loss on the basis of actual prediction and the target
def binary_cross_entropy_loss(prediction,target):
  epsilon = 1e-8
  prediction = torch.clamp(prediction,epsilon,1-epsilon)
  loss = -(target * torch.log(prediction) + (1-target) * torch.log(1-prediction))
  return loss


In [18]:
# Forward pass :
z = w*x +b
## sigmoid
y_pred = torch.sigmoid(z)
loss = binary_cross_entropy_loss(y_pred,y)


In [19]:
loss

tensor(6.7012)

Simplified / Forward Pass

In [20]:
x = torch.tensor(6.7)
y = torch.tensor(0)

w = torch.tensor(1.0,requires_grad=True)
b = torch.tensor(0.0,requires_grad=True)


In [22]:
z = w*x +b
z

tensor(6.7000, grad_fn=<AddBackward0>)

In [23]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9988, grad_fn=<SigmoidBackward0>)

In [24]:
loss = binary_cross_entropy_loss(y_pred,y)

In [25]:
loss

tensor(6.7012, grad_fn=<NegBackward0>)

In [43]:
loss.backward() #Backward direction

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [32]:
w.grad

tensor(6.6918)

In [28]:
b.grad

tensor(0.9988)

In [34]:
x = torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [39]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [40]:
y.backward()

In [41]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

Clear grad

In [42]:
x.grad.zero_()

tensor([0., 0., 0.])

In [44]:
x.requires_grad_(False)

tensor([1., 2., 3.])

In [45]:
v = torch.tensor([1.0,2.0,3.0],requires_grad=True)
v

tensor([1., 2., 3.], requires_grad=True)

In [46]:
with torch.no_grad():
  y = x**2
y

tensor([1., 4., 9.])

In [47]:
y.backward()

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn