In [1]:
import torch
print(torch.__version__)

2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("cuda is available")
else:
    print("cuda is not available")

cuda is available


### Creating a Tensor

In [6]:
# using empty
a = torch.empty(2,3) ##shape


In [7]:
# type of tensor
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
#using rand -> value from 0 to 1 randomly
torch.rand(2,3)


tensor([[0.7352, 0.0351, 0.9845],
        [0.1487, 0.6343, 0.2330]])

In [13]:
#manual seed
torch.manual_seed(100) # give same random value
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [17]:
#Linspace :linearly spaced
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [18]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

Tensor Shapes


In [19]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [20]:
x.shape

torch.Size([2, 3])

In [21]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])